# ============================================================================
# MODULE 07B: COMPREHENSIVE GRASSLAND STANDARDS COMPLIANCE REPORT
# ============================================================================
# PURPOSE: Generate comprehensive report with all figures, maps, and outputs
#          from Modules 01-07, with detailed standards compliance checking and
#          actionable recommendations for Canadian grassland carbon projects
#
# STANDARDS COVERED:
#   - VCS VM0026 - Avoided Grassland Conversion
#   - VCS VM0032 - Improved Grassland Management
#   - VCS VM0042 - Improved Agricultural Land Management
#   - Alberta TIER - Technology Innovation and Emissions Reduction
#   - Canadian Agricultural GHG Methodology (IPCC Tier 3)
#
# INPUTS:
#   - All outputs from Modules 01-07 (carbon stocks, predictions, diagnostics)
#   - All figures and maps generated by previous modules
#   - Cross-validation results, uncertainty estimates
#   - Field data quality metrics
#   - Grazing management compliance data
#
# OUTPUTS:
#   - outputs/reports/comprehensive_grassland_standards_report.html
#   - outputs/reports/grassland_standards_compliance_summary.csv
#   - outputs/reports/grassland_recommendations_action_plan.csv
# ============================================================================

# Clear workspace
rm(list = ls())

# Load required libraries
suppressPackageStartupMessages({
  library(terra)
  library(sf)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(readr)
  library(gridExtra)
})

# Load configuration
source("grassland_carbon_config.R")

# ============================================================================
# SETUP LOGGING
# ============================================================================

log_message <- function(msg, level = "INFO") {
  timestamp <- format(Sys.time(), "[%Y-%m-%d %H:%M:%S]")
  cat(sprintf("%s %s: %s\n", timestamp, level, msg))
}

log_message("=== MODULE 07B: COMPREHENSIVE GRASSLAND STANDARDS COMPLIANCE REPORT ===")
log_message(sprintf("Project: %s", PROJECT_NAME))

# Create output directories
dir.create("outputs/reports", recursive = TRUE, showWarnings = FALSE)
dir.create("outputs/reports/figures", recursive = TRUE, showWarnings = FALSE)

# ============================================================================
# VALIDATION FUNCTIONS
# ============================================================================

# Validate carbon stocks data structure
validate_carbon_stocks <- function(carbon_stocks) {

  required_cols <- c(
    "stratum",
    "mean_stock_0_100_Mg_ha",
    "conservative_stock_0_100_Mg_ha",
    "mean_stock_0_30_Mg_ha",  # Primary for grassland
    "total_stock_0_100_Mg"
  )

  missing_cols <- setdiff(required_cols, names(carbon_stocks))

  if (length(missing_cols) > 0) {
    log_message(sprintf("WARNING: Carbon stocks missing expected columns: %s",
                        paste(missing_cols, collapse=", ")), "WARNING")
    log_message(sprintf("Available columns: %s",
                        paste(names(carbon_stocks), collapse=", ")), "INFO")
    return(FALSE)
  }

  return(TRUE)
}

log_message("Validation functions defined")

# ============================================================================
# GRASSLAND STANDARDS COMPLIANCE CRITERIA
# ============================================================================

log_message("\nDefining grassland standards compliance criteria...")

# VCS VM0026 - Avoided Grassland Conversion
vm0026_criteria <- list(
  name = "VCS VM0026 - Avoided Grassland Conversion",
  requirements = list(
    list(
      criterion = "Minimum samples per stratum",
      threshold = VM0026_MIN_CORES,
      check_function = function(data) {
        if (is.null(data$cores)) return(list(pass = FALSE, value = NA, message = "No core data"))

        samples_per_stratum <- data$cores %>%
          group_by(stratum) %>%
          summarise(n_cores = n_distinct(core_id), .groups = "drop")

        min_samples <- min(samples_per_stratum$n_cores, na.rm = TRUE)
        pass <- all(samples_per_stratum$n_cores >= VM0026_MIN_CORES)

        message <- if (pass) {
          sprintf("All strata have ≥%d samples (min: %d)", VM0026_MIN_CORES, min_samples)
        } else {
          failing_strata <- samples_per_stratum %>%
            filter(n_cores < VM0026_MIN_CORES)
          sprintf("FAIL: %d strata below minimum (%s)",
                  nrow(failing_strata),
                  paste(failing_strata$stratum, collapse = ", "))
        }

        list(pass = pass, value = min_samples, message = message,
             details = samples_per_stratum)
      }
    ),
    list(
      criterion = "Grassland depth intervals measured",
      threshold = "0-15, 15-30, 30-50, 50-100 cm",
      check_function = function(data) {
        if (is.null(data$cores)) return(list(pass = FALSE, value = NA, message = "No core data"))

        required_depths <- GRASSLAND_DEPTH_MIDPOINTS
        available_depths <- unique(data$cores$depth_midpoint_cm)

        has_all_depths <- all(required_depths %in% available_depths)

        message <- if (has_all_depths) {
          "All grassland standard depths present"
        } else {
          missing <- setdiff(required_depths, available_depths)
          sprintf("FAIL: Missing depths: %s cm", paste(missing, collapse = ", "))
        }

        list(pass = has_all_depths,
             value = length(available_depths),
             message = message,
             details = list(required = required_depths, available = available_depths))
      }
    ),
    list(
      criterion = "SOC range validity (grassland soils)",
      threshold = "10-150 g/kg",
      check_function = function(data) {
        if (is.null(data$cores)) return(list(pass = FALSE, value = NA, message = "No core data"))

        soc_range <- range(data$cores$soc_g_kg, na.rm = TRUE)
        within_range <- soc_range[1] >= QC_SOC_MIN && soc_range[2] <= QC_SOC_MAX

        message <- if (within_range) {
          sprintf("SOC range valid: %.1f-%.1f g/kg", soc_range[1], soc_range[2])
        } else {
          sprintf("WARNING: SOC outside expected range (%.1f-%.1f g/kg)", soc_range[1], soc_range[2])
        }

        list(pass = within_range, value = paste(round(soc_range, 1), collapse = "-"),
             message = message)
      }
    ),
    list(
      criterion = "Bulk density range validity (grassland soils)",
      threshold = "0.8-1.6 g/cm³",
      check_function = function(data) {
        if (is.null(data$cores)) return(list(pass = FALSE, value = NA, message = "No core data"))

        bd_range <- range(data$cores$bulk_density_g_cm3, na.rm = TRUE)
        within_range <- bd_range[1] >= QC_BD_MIN && bd_range[2] <= QC_BD_MAX

        message <- if (within_range) {
          sprintf("Bulk density range valid: %.2f-%.2f g/cm³", bd_range[1], bd_range[2])
        } else {
          sprintf("WARNING: Bulk density outside expected range (%.2f-%.2f g/cm³)", bd_range[1], bd_range[2])
        }

        list(pass = within_range, value = paste(round(bd_range, 2), collapse = "-"),
             message = message)
      }
    ),
    list(
      criterion = "Conservative estimates used",
      threshold = "95% CI lower bound",
      check_function = function(data) {
        if (is.null(data$carbon_stocks)) return(list(pass = FALSE, value = NA, message = "No carbon stock data"))

        has_conservative <- "conservative_stock_0_100_Mg_ha" %in% names(data$carbon_stocks)

        if (has_conservative) {
          stocks <- data$carbon_stocks %>%
            filter(stratum != "ALL", !is.na(conservative_stock_0_100_Mg_ha))

          all_conservative_lower <- all(stocks$conservative_stock_0_100_Mg_ha < stocks$mean_stock_0_100_Mg_ha)

          message <- if (all_conservative_lower) {
            sprintf("Conservative estimates properly calculated (%d strata)", nrow(stocks))
          } else {
            "FAIL: Some conservative estimates ≥ mean"
          }

          list(pass = all_conservative_lower, value = "Yes", message = message)
        } else {
          list(pass = FALSE, value = "No", message = "FAIL: Conservative estimates not calculated")
        }
      }
    )
  )
)

# VCS VM0032 - Improved Grassland Management
vm0032_criteria <- list(
  name = "VCS VM0032 - Improved Grassland Management",
  requirements = list(
    list(
      criterion = "Minimum samples per stratum",
      threshold = VM0032_MIN_CORES,
      check_function = function(data) {
        if (is.null(data$cores)) return(list(pass = FALSE, value = NA, message = "No core data"))

        samples_per_stratum <- data$cores %>%
          group_by(stratum) %>%
          summarise(n_cores = n_distinct(core_id), .groups = "drop")

        min_samples <- min(samples_per_stratum$n_cores, na.rm = TRUE)
        pass <- all(samples_per_stratum$n_cores >= VM0032_MIN_CORES)

        message <- if (pass) {
          sprintf("All strata have ≥%d samples", VM0032_MIN_CORES)
        } else {
          sprintf("FAIL: Some strata below minimum %d samples", VM0032_MIN_CORES)
        }

        list(pass = pass, value = min_samples, message = message)
      }
    ),
    list(
      criterion = "Grazing management documentation",
      threshold = "Required for improved management credits",
      check_function = function(data) {
        # Check if grazing variables are documented
        # This would require checking field data for grazing_history, stocking_rate, etc.
        message <- "INFO: Verify grazing management data is documented (stocking rates, rest periods, system type)"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Baseline vs project comparison",
      threshold = "Required for additionality",
      check_function = function(data) {
        # This requires temporal analysis (Module 09)
        message <- "INFO: Baseline scenario comparison required (see Module 09 temporal analysis)"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Monitoring frequency",
      threshold = paste0("Every ", GRASSLAND_MONITORING_FREQUENCY, " years"),
      check_function = function(data) {
        message <- sprintf("Requirement: Monitoring every %d years (temporal module needed)",
                          GRASSLAND_MONITORING_FREQUENCY)
        list(pass = NA, value = "N/A", message = message)
      }
    )
  )
)

# VCS VM0042 - Improved Agricultural Land Management
vm0042_criteria <- list(
  name = "VCS VM0042 - Improved Agricultural Land Management",
  requirements = list(
    list(
      criterion = "Soil carbon pool measurement (0-30 cm focus)",
      threshold = "Primary depth 0-30 cm",
      check_function = function(data) {
        if (is.null(data$carbon_stocks)) return(list(pass = FALSE, value = NA, message = "No carbon stock data"))

        has_0_30 <- "mean_stock_0_30_Mg_ha" %in% names(data$carbon_stocks)

        message <- if (has_0_30) {
          "Primary depth interval (0-30 cm) calculated"
        } else {
          "FAIL: Primary depth interval (0-30 cm) not calculated"
        }

        list(pass = has_0_30, value = has_0_30, message = message)
      }
    ),
    list(
      criterion = "Soil texture documentation (clay content)",
      threshold = "Required for SOC stability assessment",
      check_function = function(data) {
        # Check if soil texture is documented
        message <- "INFO: Verify soil texture data (% clay) is documented for all sites"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Management history documentation",
      threshold = "Required for crediting",
      check_function = function(data) {
        message <- "INFO: Verify management history documented (tillage, fertilization, fire)"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Cross-validation performed",
      threshold = "Required for spatial predictions",
      check_function = function(data) {
        cv_exists <- !is.null(data$cv_results) && nrow(data$cv_results) > 0

        message <- if (cv_exists) {
          mean_r2 <- mean(data$cv_results$cv_r2, na.rm = TRUE)
          sprintf("Cross-validation performed (mean R²: %.3f)", mean_r2)
        } else {
          "FAIL: No cross-validation results found"
        }

        list(pass = cv_exists, value = cv_exists, message = message)
      }
    )
  )
)

# Alberta TIER Offset Protocol
alberta_tier_criteria <- list(
  name = "Alberta TIER - Grassland Carbon Offsets",
  requirements = list(
    list(
      criterion = "Minimum samples per stratum",
      threshold = ALBERTA_TIER_MIN_CORES,
      check_function = function(data) {
        if (is.null(data$cores)) return(list(pass = FALSE, value = NA, message = "No core data"))

        samples_per_stratum <- data$cores %>%
          group_by(stratum) %>%
          summarise(n_cores = n_distinct(core_id), .groups = "drop")

        min_samples <- min(samples_per_stratum$n_cores, na.rm = TRUE)
        pass <- all(samples_per_stratum$n_cores >= ALBERTA_TIER_MIN_CORES)

        message <- if (pass) {
          sprintf("All strata meet TIER minimum (%d cores)", ALBERTA_TIER_MIN_CORES)
        } else {
          sprintf("FAIL: Some strata below TIER minimum", ALBERTA_TIER_MIN_CORES)
        }

        list(pass = pass, value = min_samples, message = message)
      }
    ),
    list(
      criterion = "Alberta-specific parameters",
      threshold = "Provincial calibration recommended",
      check_function = function(data) {
        # Check if Alberta-specific bulk density and SOC parameters are used
        message <- "INFO: Verify Alberta-specific soil parameters used (BD, SOC baselines)"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Crediting period compliance",
      threshold = paste0(TIER_CREDITING_PERIOD_YEARS, " years"),
      check_function = function(data) {
        message <- sprintf("INFO: TIER crediting period is %d years", TIER_CREDITING_PERIOD_YEARS)

        list(pass = NA, value = "N/A", message = message)
      }
    )
  )
)

# Canadian Agricultural GHG Methodology (IPCC Tier 3)
canada_ipcc_criteria <- list(
  name = "Canadian Agricultural GHG Methodology (IPCC Tier 3)",
  requirements = list(
    list(
      criterion = "Tier 3 approach (site-specific data)",
      threshold = "Required for high accuracy",
      check_function = function(data) {
        has_field_data <- !is.null(data$cores) && nrow(data$cores) > 0
        n_cores <- if (has_field_data) n_distinct(data$cores$core_id) else 0

        tier <- if (n_cores >= 10) {
          "Tier 3"
        } else if (n_cores >= 3) {
          "Tier 2/3"
        } else {
          "Tier 1/2"
        }

        message <- sprintf("%s approach (%d field cores)", tier, n_cores)

        list(pass = n_cores >= 3, value = tier, message = message)
      }
    ),
    list(
      criterion = "Uncertainty quantification",
      threshold = "95% confidence intervals",
      check_function = function(data) {
        if (is.null(data$carbon_stocks)) return(list(pass = FALSE, value = NA, message = "No carbon stock data"))

        has_uncertainty <- "conservative_stock_0_100_Mg_ha" %in% names(data$carbon_stocks)

        message <- if (has_uncertainty) {
          "Uncertainty quantified with 95% CI"
        } else {
          "FAIL: Uncertainty not quantified"
        }

        list(pass = has_uncertainty, value = has_uncertainty, message = message)
      }
    ),
    list(
      criterion = "Canadian spatial context",
      threshold = "Canadian provincial CRS",
      check_function = function(data) {
        # Canadian CRS codes (provincial and national)
        canadian_crs <- c(
          3347,  # Canada Albers
          3400, 3402,  # Alberta 10-TM
          2955, 2151,  # Saskatchewan
          2957, 3158,  # Manitoba
          32612, 32613, 32614, 32615  # UTM zones covering prairies
        )

        is_canadian_crs <- PROCESSING_CRS %in% canadian_crs

        crs_name <- switch(as.character(PROCESSING_CRS),
          "3347" = "Canada Albers",
          "3400" = "Alberta 10-TM Resource",
          "3402" = "Alberta 10-TM Forest",
          "2955" = "Saskatchewan UTM 13N",
          "2957" = "Manitoba UTM 14N",
          sprintf("UTM zone %d", PROCESSING_CRS)
        )

        message <- if (is_canadian_crs) {
          sprintf("Canadian CRS used: EPSG:%d (%s)", PROCESSING_CRS, crs_name)
        } else {
          sprintf("WARNING: Non-Canadian CRS (EPSG:%d) - consider using provincial CRS", PROCESSING_CRS)
        }

        list(pass = is_canadian_crs, value = PROCESSING_CRS, message = message)
      }
    ),
    list(
      criterion = "Target precision (relative error at 95% CI)",
      threshold = paste0("≤", GRASSLAND_TARGET_PRECISION, "%"),
      check_function = function(data) {
        if (is.null(data$carbon_stocks)) return(list(pass = FALSE, value = NA, message = "No carbon stock data"))

        stocks <- data$carbon_stocks %>%
          filter(stratum != "ALL") %>%
          mutate(
            relative_error = ifelse(mean_stock_0_100_Mg_ha > 0,
                                   100 * (mean_stock_0_100_Mg_ha - conservative_stock_0_100_Mg_ha) / mean_stock_0_100_Mg_ha,
                                   NA)
          )

        max_error <- max(stocks$relative_error, na.rm = TRUE)
        pass <- max_error <= GRASSLAND_TARGET_PRECISION

        message <- if (pass) {
          sprintf("All strata within target (max: %.1f%%)", max_error)
        } else {
          failing_strata <- stocks %>% filter(relative_error > GRASSLAND_TARGET_PRECISION)
          sprintf("WARNING: %d strata exceed %.0f%% (max: %.1f%%)",
                  nrow(failing_strata), GRASSLAND_TARGET_PRECISION, max_error)
        }

        list(pass = pass, value = max_error, message = message, details = stocks)
      }
    )
  )
)

# ECCC (Environment and Climate Change Canada) - National GHG Inventory
eccc_criteria <- list(
  name = "ECCC - National GHG Inventory Standards",
  requirements = list(
    list(
      criterion = "Grassland land use classification",
      threshold = "IPCC land use categories",
      check_function = function(data) {
        # Check if grassland types align with IPCC categories
        # Grassland remaining grassland vs. Land converted to grassland
        message <- "INFO: Verify land use classification matches IPCC categories (Grassland Remaining Grassland or Land Converted to Grassland)"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "NIR reporting compatibility",
      threshold = "Compatible with National Inventory Report format",
      check_function = function(data) {
        # Check if data can be reported in NIR format
        message <- "INFO: Ensure data format compatible with Canada's National Inventory Report (NIR) requirements"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "QA/QC procedures",
      threshold = "ECCC QA/QC standards",
      check_function = function(data) {
        has_qc <- !is.null(data$cores) && nrow(data$cores) > 0

        message <- if (has_qc) {
          "QA/QC data available (verify against ECCC standards)"
        } else {
          "WARNING: No QA/QC data found"
        }

        list(pass = has_qc, value = has_qc, message = message)
      }
    )
  )
)

# Provincial Standards (Alberta example - adapt for SK, MB as needed)
provincial_criteria <- list(
  name = "Alberta Provincial Grassland Standards",
  requirements = list(
    list(
      criterion = "Natural subregion classification",
      threshold = "Alberta Natural Regions",
      check_function = function(data) {
        # Check if project location matches Alberta natural subregions
        # Grassland: Dry Mixedgrass, Mixed Grassland, Northern Fescue, Foothills Fescue
        message <- sprintf("INFO: Project location: %s. Verify alignment with Alberta Natural Subregions classification",
                          PROJECT_LOCATION)

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Provincial SOC baselines",
      threshold = "Alberta soil carbon reference values",
      check_function = function(data) {
        if (is.null(data$carbon_stocks)) return(list(pass = FALSE, value = NA, message = "No carbon stock data"))

        # Check if SOC values are within Alberta grassland range
        # Alberta mixed grassland: typically 40-70 Mg C/ha (0-30 cm)
        stocks_0_30 <- data$carbon_stocks %>%
          filter(stratum != "ALL") %>%
          pull(mean_stock_0_30_Mg_ha)

        alberta_range <- stocks_0_30 >= 30 && stocks_0_30 <= 90

        message <- if (all(alberta_range, na.rm = TRUE)) {
          sprintf("SOC values within Alberta grassland range (%.1f-%.1f Mg C/ha)",
                  min(stocks_0_30, na.rm = TRUE), max(stocks_0_30, na.rm = TRUE))
        } else {
          "WARNING: Some SOC values outside typical Alberta grassland range (30-90 Mg C/ha 0-30cm)"
        }

        list(pass = all(alberta_range, na.rm = TRUE), value = mean(stocks_0_30, na.rm = TRUE),
             message = message)
      }
    ),
    list(
      criterion = "Grazing management documentation (provincial)",
      threshold = "Alberta sustainable grazing guidelines",
      check_function = function(data) {
        # Check for grazing management data
        message <- "INFO: Verify grazing practices align with Alberta Beef Producers Environmental Stewardship guidelines"

        list(pass = NA, value = "N/A", message = message)
      }
    ),
    list(
      criterion = "Native prairie retention",
      threshold = "Provincial biodiversity objectives",
      check_function = function(data) {
        # Check if native prairie reference sites are included
        has_native <- if (!is.null(data$cores)) {
          "Native Prairie" %in% unique(data$cores$stratum)
        } else {
          FALSE
        }

        message <- if (has_native) {
          "Native prairie reference sites included (supports provincial conservation objectives)"
        } else {
          "INFO: Consider including native prairie reference for biodiversity co-benefits"
        }

        list(pass = has_native, value = has_native, message = message)
      }
    )
  )
)

# Store all grassland standards
all_standards <- list(
  VM0026 = vm0026_criteria,
  VM0032 = vm0032_criteria,
  VM0042 = vm0042_criteria,
  Alberta_TIER = alberta_tier_criteria,
  Canada_IPCC = canada_ipcc_criteria,
  ECCC = eccc_criteria,
  Provincial = provincial_criteria
)

# ============================================================================
# LOAD ALL AVAILABLE DATA
# ============================================================================

log_message("\nLoading all available data from workflow...")

workflow_data <- list(
  cores = NULL,
  carbon_stocks = NULL,
  cv_results = NULL,
  qc_summary = NULL,
  spatial_predictions = list(),
  diagnostics = list()
)

# Load harmonized cores
if (file.exists("data_processed/cores_harmonized_grassland.rds")) {
  workflow_data$cores <- readRDS("data_processed/cores_harmonized_grassland.rds")
  log_message(sprintf("  Loaded %d cores from %d sites",
                     nrow(workflow_data$cores),
                     n_distinct(workflow_data$cores$core_id)))
} else if (file.exists("data_processed/cores_harmonized_bluecarbon.rds")) {
  # Fallback to blue carbon naming
  workflow_data$cores <- readRDS("data_processed/cores_harmonized_bluecarbon.rds")
  log_message(sprintf("  Loaded %d cores (using blue carbon naming)",
                     nrow(workflow_data$cores),
                     n_distinct(workflow_data$cores$core_id)))
} else {
  log_message("  Harmonized cores not found", "WARNING")
}

# Load carbon stocks (try both RF and Kriging, both naming conventions)
for (method in c("rf", "kriging")) {
  for (ecosystem in c("grassland", "bluecarbon")) {
    vm_file <- sprintf("outputs/carbon_stocks/carbon_stocks_conservative_vm0026_%s.csv", method)
    generic_file <- sprintf("outputs/carbon_stocks/carbon_stocks_conservative_%s_%s.csv", ecosystem, method)

    file_to_try <- if (file.exists(vm_file)) vm_file else generic_file

    if (file.exists(file_to_try)) {
      stocks <- tryCatch({
        read.csv(file_to_try)
      }, error = function(e) {
        log_message(sprintf("  Could not load %s carbon stocks: %s", method, e$message), "WARNING")
        NULL
      })

      if (!is.null(stocks) && nrow(stocks) > 0) {
        stocks$method <- method
        workflow_data$carbon_stocks <- rbind(workflow_data$carbon_stocks, stocks)
        log_message(sprintf("  Loaded %s carbon stocks", method))
        break  # Found data, no need to try other naming convention
      }
    }
  }
}

# Load cross-validation results
for (method in c("rf", "kriging")) {
  cv_file <- sprintf("diagnostics/crossvalidation/%s_cv_results.csv", method)
  if (file.exists(cv_file)) {
    cv_data <- tryCatch({
      read.csv(cv_file)
    }, error = function(e) {
      log_message(sprintf("  Could not load %s CV results: %s", method, e$message), "WARNING")
      NULL
    })

    if (!is.null(cv_data) && nrow(cv_data) > 0) {
      cv_data$method <- method
      workflow_data$cv_results <- rbind(workflow_data$cv_results, cv_data)
      log_message(sprintf("  Loaded %s CV results", method))
    }
  }
}

# Count available spatial predictions
for (method in c("rf", "kriging")) {
  pred_dir <- file.path("outputs/predictions", method)
  if (dir.exists(pred_dir)) {
    pred_files <- list.files(pred_dir, pattern = "\\.tif$", full.names = TRUE)
    workflow_data$spatial_predictions[[method]] <- pred_files
    log_message(sprintf("  Found %d %s prediction rasters", length(pred_files), method))
  }
}

log_message("Data loading complete")

# Validate loaded carbon stocks data structure
if (!is.null(workflow_data$carbon_stocks)) {
  log_message("\nValidating carbon stocks data structure...")
  if (!validate_carbon_stocks(workflow_data$carbon_stocks)) {
    log_message("Carbon stocks validation failed - some checks may fail", "WARNING")
  } else {
    log_message("Carbon stocks validation passed")
  }
}

# ============================================================================
# RUN COMPLIANCE CHECKS FOR ALL STANDARDS
# ============================================================================

log_message("\n=== RUNNING GRASSLAND STANDARDS COMPLIANCE CHECKS ===")

compliance_results <- list()

for (standard_name in names(all_standards)) {
  standard <- all_standards[[standard_name]]

  log_message(sprintf("\nChecking: %s", standard$name))

  standard_results <- list(
    standard_name = standard$name,
    checks = list(),
    pass_count = 0,
    fail_count = 0,
    warning_count = 0,
    na_count = 0
  )

  for (req in standard$requirements) {
    log_message(sprintf("  Checking: %s", req$criterion))

    result <- tryCatch({
      req$check_function(workflow_data)
    }, error = function(e) {
      list(pass = FALSE, value = NA, message = paste("ERROR:", e$message))
    })

    result$criterion <- req$criterion
    result$threshold <- req$threshold

    # Count outcomes
    if (is.na(result$pass)) {
      standard_results$na_count <- standard_results$na_count + 1
    } else if (result$pass) {
      standard_results$pass_count <- standard_results$pass_count + 1
    } else {
      standard_results$fail_count <- standard_results$fail_count + 1
    }

    standard_results$checks[[req$criterion]] <- result

    log_message(sprintf("    %s", result$message))
  }

  compliance_results[[standard_name]] <- standard_results
}

# ============================================================================
# GENERATE GRASSLAND-SPECIFIC RECOMMENDATIONS
# ============================================================================

log_message("\n=== GENERATING GRASSLAND RECOMMENDATIONS ===")

recommendations <- list()

# Recommendation 1: Sample size improvements
if (!is.null(workflow_data$cores)) {
  samples_per_stratum <- workflow_data$cores %>%
    group_by(stratum) %>%
    summarise(n_cores = n_distinct(core_id), .groups = "drop")

  understrata <- samples_per_stratum %>%
    filter(n_cores < VM0026_MIN_CORES)

  if (nrow(understrata) > 0) {
    for (i in 1:nrow(understrata)) {
      needed <- VM0026_MIN_CORES - understrata$n_cores[i]
      recommendations[[length(recommendations) + 1]] <- list(
        priority = "HIGH",
        category = "Sampling",
        recommendation = sprintf("Collect %d additional cores in '%s' stratum to meet VM0026/VM0032 minimum (%d cores currently, %d required)",
                                needed, understrata$stratum[i], understrata$n_cores[i], VM0026_MIN_CORES),
        standard = "VM0026/VM0032",
        action = sprintf("Add %d cores", needed)
      )
    }
  }
}

# Recommendation 2: Grazing management documentation
if (CHECK_GRAZING_COMPLIANCE) {
  recommendations[[length(recommendations) + 1]] <- list(
    priority = "HIGH",
    category = "Management Documentation",
    recommendation = "Document grazing management practices: stocking rates (AUM/ha), grazing system (rotational/continuous), rest periods, and utilization rates. Required for VM0032 improved management credits.",
    standard = "VM0032",
    action = "Complete grazing management survey"
  )
}

# Recommendation 3: Soil texture analysis
recommendations[[length(recommendations) + 1]] <- list(
  priority = "MEDIUM",
  category = "Soil Analysis",
  recommendation = "Analyze soil texture (% clay, silt, sand) for all cores. Clay content is crucial for SOC stability assessment and required for VM0042 crediting. Target: clay content for all sites.",
  standard = "VM0042",
  action = "Laboratory texture analysis"
)

# Recommendation 4: Species composition survey
recommendations[[length(recommendations) + 1]] <- list(
  priority = "MEDIUM",
  category = "Ecological Monitoring",
  recommendation = "Conduct vegetation surveys to document % native species, C3/C4 grass composition, and invasive species presence. Required for VM0026 avoided conversion projects.",
  standard = "VM0026",
  action = "Vegetation composition survey"
)

# Recommendation 5: Spatial validation improvements
if (!is.null(workflow_data$cv_results)) {
  poor_cv <- workflow_data$cv_results %>%
    filter(cv_r2 < 0.5)

  if (nrow(poor_cv) > 0) {
    recommendations[[length(recommendations) + 1]] <- list(
      priority = "MEDIUM",
      category = "Model Performance",
      recommendation = "Improve spatial model performance (R² < 0.5). Consider: (1) Adding climate covariates (GDD, precipitation), (2) Including soil texture data, (3) Incorporating topographic wetness index, (4) Increasing sample size in poorly predicted areas.",
      standard = "All standards",
      action = "Improve model covariates or sampling"
    )
  }
}

# Recommendation 6: Temporal monitoring setup
if (MONITORING_YEAR == format(Sys.Date(), "%Y")) {
  recommendations[[length(recommendations) + 1]] <- list(
    priority = "MEDIUM",
    category = "Monitoring",
    recommendation = sprintf("Establish baseline monitoring. Next verification required in %d years (Year %d) per VM0026/VM0032 requirements. Use permanent plot markers for repeat sampling.",
                            GRASSLAND_MONITORING_FREQUENCY,
                            as.numeric(MONITORING_YEAR) + GRASSLAND_MONITORING_FREQUENCY),
    standard = "VM0026/VM0032",
    action = sprintf("Schedule %d monitoring", as.numeric(MONITORING_YEAR) + GRASSLAND_MONITORING_FREQUENCY)
  )
}

# Recommendation 7: Root biomass assessment
recommendations[[length(recommendations) + 1]] <- list(
  priority = "LOW",
  category = "Carbon Pool Enhancement",
  recommendation = "Consider root biomass assessment (0-30 cm) for complete carbon accounting. Grasslands store 60-80% of carbon belowground. Root:shoot ratios can be estimated from literature or measured directly.",
  standard = "All standards",
  action = "Optional: root biomass cores"
)

# If no high/medium recommendations, add positive note
high_medium <- sum(sapply(recommendations, function(r) r$priority %in% c("HIGH", "MEDIUM")))
if (high_medium == 0) {
  recommendations[[1]] <- list(
    priority = "INFO",
    category = "Status",
    recommendation = "All critical grassland standards compliance criteria met! Workflow is verification-ready for VM0026/VM0032/VM0042/TIER crediting.",
    standard = "All",
    action = "Proceed to verification"
  )
}

log_message(sprintf("Generated %d recommendations", length(recommendations)))

# ============================================================================
# CREATE COMPREHENSIVE GRASSLAND REPORT
# ============================================================================

log_message("\nGenerating comprehensive HTML report...")

# Convert recommendations to data frame
recommendations_df <- do.call(rbind, lapply(recommendations, as.data.frame))

# Convert compliance results to data frame
compliance_summary <- do.call(rbind, lapply(names(compliance_results), function(std_name) {
  std <- compliance_results[[std_name]]
  data.frame(
    Standard = std$standard_name,
    Total_Checks = length(std$checks),
    Passed = std$pass_count,
    Failed = std$fail_count,
    Warnings = std$warning_count,
    NA_Checks = std$na_count,
    Compliance_Rate = round(100 * std$pass_count / max(1, (std$pass_count + std$fail_count)), 1)
  )
}))

# Save CSVs
write_csv(compliance_summary, "outputs/reports/grassland_standards_compliance_summary.csv")
write_csv(recommendations_df, "outputs/reports/grassland_recommendations_action_plan.csv")

log_message("  Saved grassland_standards_compliance_summary.csv")
log_message("  Saved grassland_recommendations_action_plan.csv")

# ============================================================================
# BUILD HTML REPORT
# ============================================================================

html_content <- sprintf('
<!DOCTYPE html>
<html>
<head>
<title>%s - Comprehensive Grassland Standards Report</title>
<style>
body {
  font-family: Arial, sans-serif;
  margin: 40px;
  background-color: #f5f5f5;
}
.header {
  background-color: #2c3e50;
  color: white;
  padding: 20px;
  margin: -40px -40px 40px -40px;
}
h1 { margin: 0; }
h2 {
  color: #2c3e50;
  border-bottom: 2px solid: #27ae60;
  padding-bottom: 10px;
  margin-top: 40px;
}
h3 {
  color: #34495e;
  margin-top: 30px;
}
.meta-info {
  background-color: white;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 20px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}
table {
  width: 100%%;
  border-collapse: collapse;
  background-color: white;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  margin-bottom: 30px;
}
th {
  background-color: #27ae60;
  color: white;
  padding: 12px;
  text-align: left;
}
td {
  padding: 10px;
  border-bottom: 1px solid #ddd;
}
tr:nth-child(even) {
  background-color: #f9f9f9;
}
.pass {
  background-color: #2ecc71;
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: bold;
}
.fail {
  background-color: #e74c3c;
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: bold;
}
.warning {
  background-color: #f39c12;
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: bold;
}
.na {
  background-color: #95a5a6;
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: bold;
}
.priority-high {
  color: #e74c3c;
  font-weight: bold;
}
.priority-medium {
  color: #f39c12;
  font-weight: bold;
}
.priority-low {
  color: #27ae60;
}
.summary-box {
  background-color: white;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 20px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}
.stat {
  display: inline-block;
  margin-right: 30px;
  font-size: 18px;
}
.stat-value {
  font-size: 32px;
  font-weight: bold;
  color: #27ae60;
}
</style>
</head>
<body>

<div class="header">
<h1>Comprehensive Canadian Grassland Standards Compliance Report</h1>
<p style="margin: 10px 0 0 0; font-size: 16px;">%s</p>
</div>

<div class="meta-info">
<h3>Project Information</h3>
<p><strong>Project Name:</strong> %s</p>
<p><strong>Project Scenario:</strong> %s</p>
<p><strong>Monitoring Year:</strong> %d</p>
<p><strong>Report Generated:</strong> %s</p>
<p><strong>Location:</strong> %s</p>
<p><strong>Standards:</strong> VM0026, VM0032, VM0042, Alberta TIER, Canadian IPCC Tier 3, ECCC NIR, Provincial</p>
</div>

<h2>Executive Summary</h2>

<div class="summary-box">
',
PROJECT_NAME,
PROJECT_DESCRIPTION,
PROJECT_NAME,
PROJECT_SCENARIO,
MONITORING_YEAR,
format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
PROJECT_LOCATION)

# Add summary statistics
if (!is.null(workflow_data$cores)) {
  n_cores <- n_distinct(workflow_data$cores$core_id)
  n_strata <- n_distinct(workflow_data$cores$stratum)
  html_content <- paste0(html_content, sprintf('
<div class="stat">
  <div class="stat-value">%d</div>
  <div>Field Cores</div>
</div>
<div class="stat">
  <div class="stat-value">%d</div>
  <div>Grassland Strata</div>
</div>
', n_cores, n_strata))
}

if (!is.null(workflow_data$carbon_stocks)) {
  total_stock <- workflow_data$carbon_stocks %>%
    filter(stratum == "ALL") %>%
    slice(1) %>%
    pull(total_stock_0_100_Mg)

  html_content <- paste0(html_content, sprintf('
<div class="stat">
  <div class="stat-value">%.0f</div>
  <div>Total SOC (Mg C)</div>
</div>
', total_stock))
}

html_content <- paste0(html_content, sprintf('
<div class="stat">
  <div class="stat-value">%d</div>
  <div>Standards Checked</div>
</div>
</div>

<h2>Grassland Standards Compliance Summary</h2>

<table>
<tr>
  <th>Standard</th>
  <th>Total Checks</th>
  <th>Passed</th>
  <th>Failed</th>
  <th>Warnings</th>
  <th>Compliance Rate</th>
</tr>
', length(all_standards)))

# Add compliance summary rows
for (i in 1:nrow(compliance_summary)) {
  row <- compliance_summary[i, ]

  compliance_class <- if (row$Compliance_Rate >= 90) "pass" else if (row$Compliance_Rate >= 70) "warning" else "fail"

  html_content <- paste0(html_content, sprintf('
<tr>
  <td><strong>%s</strong></td>
  <td>%d</td>
  <td>%d</td>
  <td>%d</td>
  <td>%d</td>
  <td><span class="%s">%.1f%%</span></td>
</tr>
', row$Standard, row$Total_Checks, row$Passed, row$Failed, row$Warnings,
   compliance_class, row$Compliance_Rate))
}

html_content <- paste0(html_content, '
</table>
')

# Add detailed compliance checks for each standard
html_content <- paste0(html_content, '
<h2>Detailed Compliance Checks</h2>
')

for (standard_name in names(compliance_results)) {
  std <- compliance_results[[standard_name]]

  html_content <- paste0(html_content, sprintf('
<h3>%s</h3>
<table>
<tr>
  <th>Criterion</th>
  <th>Threshold</th>
  <th>Result</th>
  <th>Status</th>
</tr>
', std$standard_name))

  for (check_name in names(std$checks)) {
    check <- std$checks[[check_name]]

    status_class <- if (is.na(check$pass)) "na" else if (check$pass) "pass" else "fail"
    status_text <- if (is.na(check$pass)) "N/A" else if (check$pass) "PASS" else "FAIL"

    html_content <- paste0(html_content, sprintf('
<tr>
  <td><strong>%s</strong></td>
  <td>%s</td>
  <td>%s</td>
  <td><span class="%s">%s</span></td>
</tr>
', check$criterion, check$threshold, check$message, status_class, status_text))
  }

  html_content <- paste0(html_content, '
</table>
')
}

# Add recommendations
html_content <- paste0(html_content, sprintf('
<h2>Recommendations & Action Plan</h2>

<p><strong>%d recommendations identified for improving grassland carbon project compliance:</strong></p>

<table>
<tr>
  <th>Priority</th>
  <th>Category</th>
  <th>Recommendation</th>
  <th>Standard</th>
  <th>Action Required</th>
</tr>
', nrow(recommendations_df)))

for (i in 1:nrow(recommendations_df)) {
  rec <- recommendations_df[i, ]

  priority_class <- paste0("priority-", tolower(rec$priority))

  html_content <- paste0(html_content, sprintf('
<tr>
  <td class="%s">%s</td>
  <td>%s</td>
  <td>%s</td>
  <td>%s</td>
  <td>%s</td>
</tr>
', priority_class, rec$priority, rec$category, rec$recommendation, rec$standard, rec$action))
}

html_content <- paste0(html_content, '
</table>

<h2>Next Steps for Grassland Carbon Crediting</h2>

<div class="summary-box">
<ol>
<li><strong>Review all recommendations</strong> and prioritize high-priority actions</li>
<li><strong>Complete management documentation</strong> (grazing history, species composition, soil texture)</li>
<li><strong>Validate spatial predictions</strong> in GIS software and check for anomalies</li>
<li><strong>Prepare baseline scenario</strong> data if pursuing improved management (VM0032) or avoided conversion (VM0026) credits</li>
<li><strong>Submit to third-party verifier</strong> with all supporting data and QA/QC logs</li>
<li><strong>Establish monitoring schedule</strong> per VM0026/VM0032 requirements (every 5 years)</li>
<li><strong>Consider root biomass assessment</strong> for comprehensive carbon accounting (60-80% belowground)</li>
</ol>
</div>

<div style="margin-top: 50px; padding: 20px; background-color: #ecf0f1; border-radius: 8px;">
<p><strong>Report generated by:</strong> Canadian Grassland Carbon MMRV Workflow</p>
<p><strong>Module:</strong> 07b_comprehensive_standards_report_grassland.R</p>
<p><strong>Configuration:</strong> grassland_carbon_config.R</p>
<p><strong>Session ID:</strong> ', SESSION_ID, '</p>
</div>

</body>
</html>
')

# Write HTML report
writeLines(html_content, "outputs/reports/comprehensive_grassland_standards_report.html")

log_message("  Saved comprehensive_grassland_standards_report.html")

# ============================================================================
# SUMMARY
# ============================================================================

cat("\n========================================\n")
cat("GRASSLAND STANDARDS REPORT COMPLETE\n")
cat("========================================\n\n")

cat("Standards Assessed:\n")
cat("-------------------\n")
for (i in 1:nrow(compliance_summary)) {
  row <- compliance_summary[i, ]
  symbol <- if (row$Compliance_Rate >= 90) "✓" else if (row$Compliance_Rate >= 70) "⚠" else "✗"
  cat(sprintf("  %s %s: %.1f%% (%d/%d checks passed)\n",
              symbol, row$Standard, row$Compliance_Rate, row$Passed, row$Total_Checks))
}

cat("\nRecommendations:\n")
cat("----------------\n")
high_priority <- sum(recommendations_df$priority == "HIGH")
medium_priority <- sum(recommendations_df$priority == "MEDIUM")
low_priority <- sum(recommendations_df$priority == "LOW")

cat(sprintf("  HIGH priority: %d\n", high_priority))
cat(sprintf("  MEDIUM priority: %d\n", medium_priority))
cat(sprintf("  LOW priority: %d\n", low_priority))

cat("\nOutput Files:\n")
cat("-------------\n")
cat("  📄 Comprehensive Report: outputs/reports/comprehensive_grassland_standards_report.html\n")
cat("  📊 Compliance Summary: outputs/reports/grassland_standards_compliance_summary.csv\n")
cat("  📋 Action Plan: outputs/reports/grassland_recommendations_action_plan.csv\n")

cat("\nKey Actions:\n")
cat("------------\n")
if (high_priority > 0) {
  cat(sprintf("  ⚠️  Address %d HIGH priority recommendations immediately\n", high_priority))
  high_rec <- recommendations_df %>% filter(priority == "HIGH")
  for (i in 1:min(3, nrow(high_rec))) {
    cat(sprintf("     %d. %s\n", i, high_rec$recommendation[i]))
  }
} else {
  cat("  ✓ No critical issues identified\n")
}

cat("\n")
log_message("=== MODULE 07B GRASSLAND COMPLETE ===")
